apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecommerce.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
  annotations:
    # IRSA: this annotation binds the Service Account to the IAM role
    # created by the terraform/modules/iam module.
    # The roleArn is injected at deploy time by the GitHub Actions workflow:
    #   helm upgrade --set serviceAccount.roleArn=$(terraform output -raw backend_sa_role_arn)
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn | quote }}